INSERT INTO Patients (Number,Surname,Name,Otchestvo,Data_Rozhdeniya) VALUES ('5',N'Шаисламов',N'Аркадий',N'Дмитриевич','3.16.2002')
INSERT INTO Patients (Number,Surname,Name,Otchestvo,Data_Rozhdeniya) VALUES ('6',N'Лихачёва',N'Анна',N'Евгеньевна','11.13.2004')
INSERT INTO Patients (Number,Surname,Name,Otchestvo,Data_Rozhdeniya) VALUES ('7',N'Тимошенко',N'Софья',N'Тимофеевна','7.4.1993')
INSERT INTO Patients (Number,Surname,Name,Otchestvo,Data_Rozhdeniya) VALUES ('8',N'Кузнецова',N'Дарья',N'Алексеева','9.3.2001')
INSERT INTO Patients (Number,Surname,Name,Otchestvo,Data_Rozhdeniya) VALUES ('9',N'Мельникова',N'Екатерина',N'Павловна','8.8.1991')
INSERT INTO Patients (Number,Surname,Name,Otchestvo,Data_Rozhdeniya) VALUES ('10',N'Колмакова',N'Александра',N'Сергеевна','6.10.1989')